=== Assylkhan/XML_POSTCARDS/src/main/resources/PostCard.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.com/assylkhan"
        xmlns:pc="http://www.example.com/assylkhan">

<complexType name="Card">
    <sequence>
        <element name="id" type="positiveInteger" />
        <element name="theme">
            <simpleType>
                <restriction base="string">
                    <enumeration value="CITY_SCENERY" />
                    <enumeration value="NATURE" />
                    <enumeration value="PEOPLE" />
                    <enumeration value="SPORT" />
                    <enumeration value="ARCHITECTURE" />
                </restriction>
            </simpleType>
        </element>
        <element name="cardType">
            <simpleType>
                <restriction base="string">
                    <enumeration value="CONGRATULATORY"/>
                    <enumeration value="ADVERTISING" />
                    <enumeration value="ORDINARY" />
                </restriction>
            </simpleType>
        </element>
        <element name="country" >
            <simpleType>
                <restriction base="string">
                    <pattern value="\w+" />
                </restriction>
            </simpleType>
        </element>
        <element name="year" type="gYear" />
        <element name="author" minOccurs="0">
            <simpleType>
                <restriction base="string">
                    <pattern value="\w+"/>
                </restriction>
            </simpleType>
        </element>
        <element name="valuable">
            <simpleType>
                <restriction base="string">
                    <enumeration value="HISTORICAL" />
                    <enumeration value="COLLECTION" />
                    <enumeration value="THEMATIC" />
                </restriction>
            </simpleType>
        </element>
    </sequence>
</complexType>
    
<element name="postCards">
    <complexType>
        <sequence>
            <element name="postCard" type="pc:Card" maxOccurs="unbounded"/>
        </sequence>
    </complexType>
</element>

</schema>

=== Assylkhan/XML_POSTCARDS/src/main/resources/PostCard.xml
<?xml version="1.0" encoding="UTF-8" ?>
<pc:postCards xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xmlns:pc="http://www.example.com/assylkhan"
             xsi:schemaLocation="http://www.example.com/assylkhan PostCard.xsd">
<postCard>
    <id>1</id>
    <theme>NATURE</theme>
    <cardType>ADVERTISING</cardType>
    <country>Germany</country>
    <year>2014</year>
    <valuable>COLLECTION</valuable>
</postCard>

<postCard>
    <id>2</id>
    <theme>CITY_SCENERY</theme>
    <cardType>CONGRATULATORY</cardType>
    <country>USA</country>
    <year>2015</year>
    <author>EPAM</author>
    <valuable>HISTORICAL</valuable>
</postCard>

<postCard>
    <id>3</id>
    <theme>ARCHITECTURE</theme>
    <cardType>ORDINARY</cardType>
    <country>Japan</country>
    <year>2017</year>
    <author>Jamato</author>
    <valuable>THEMATIC</valuable>
</postCard>
             
</pc:postCards>
